services:

  freecad:
    image: lscr.io/linuxserver/freecad:latest
    container_name: freecad
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    ports:
      - "8200:3000"
      - "8300:3001"
    restart: unless-stopped

    
